# Generated by Django 5.2.15 on 2026-06-30 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('NEEDS_REVIEW', 'Needs Review')], default='NEEDS_REVIEW', max_length=20)),
                ('packaging_ok', models.BooleanField(default=False)),
                ('physical_condition_ok', models.BooleanField(default=False)),
                ('functionality_ok', models.BooleanField(default=False)),
                ('labeling_ok', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('checked_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='inventory.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
